{block title}{_"References"}{/block}

{block content}

<div id="top" class="content">
	<h2 class="fl">{_"References"}:</h2>
	
	<ul class="submenu lava">
		{foreach $submenuItems as $id=>$value}
		<li {if isset($value['current'])}class="current"{/if}><a href="{plink References:category, 'id' => $id, 'lang' => $lang}">{!$value['name']}</a></li>
		{/foreach}
	</ul>
	<br class="cb">
</div>

<div class="line line2">&nbsp;</div>

{* one date - more references - 2 foreaches*}
{foreach $references as $date}
{foreach $date as $reference}
<div class="content reference">
	<div class="thumb fl">
	{* prints link to the first photo and next links hidden - it will allow to switch colorobox to other photos *}
	{foreach $reference['image_full'] as $k=>$full}
		{if $k==0}	{* first photo *}
		<a href="{$basePath}/files/{!$full}" class="bwswitch" rel="{$reference['id']}">
			<img src="{$basePath}/files/{$reference['image_references'][0]}" title="{!$reference['name']}" style="display: none;" class="color shadow" />
			<img src="{$basePath}/img.php?file={$reference['image_references'][0]}" title="{!$reference['name']}" class="bw shadow" />
		</a>
		{else}
		<a href="{$basePath}/files/{!$full}" rel="{$reference['id']}" style="display:none">&nbsp;</a>
		{/if}
	{/foreach}
	
	<script>
		$(document).ready(function(){
			$("a[rel='{!$reference['id']}']").colorbox();
		});
	</script>


	</div>
	<div class="info fl">
		<p class="text c-white">{!$reference['name']},<br />{!$reference['description']}</p>
		<p class="tag c-dark">{!$reference['category']}</p>
	</div>
	<br class="cb">
</div>
<div class="line line2">&nbsp;</div> 
{/foreach}
{/foreach}

<div class="content">
	{control vp}
	<!-- 
	<div class="pager">
		<ul>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
		</ul>
	</div>
	<br class="cb"> 
	-->
	
<!--	<img src="{$basePath}/img/feathers.png" id="feathers"> -->
	</div>

{/block}