{block title}{_"References"}{/block}

{block content}

<div id="top" class="content">
	<h2 class="fl">{_"References"}:</h2>
	
	<ul class="submenu lava">
		{foreach $submenuItems as $id=>$value}
		<li {if isset($value['current'])}class="current"{/if}><a href="{plink References:category, 'id' => $id}">{!$value['name']}</a></li>
		{/foreach}
	</ul>
	<br class="cb">
</div>

<div class="line line2">&nbsp;</div>

{foreach $references as $reference}
<div class="content reference">
	<div class="thumb fl">
		<a href="{$basePath}/files/{!$reference['image_full']}" class="colorbox bwswitch">
			<img src="{$basePath}/files/{$reference['image_references']}" title="{!$reference['name']}" style="display: none;" class="color" />
			<img src="{$basePath}/img.php?file={$reference['image_references']}" title="{!$reference['name']}" class="bw" />
		</a>
	</div>
	<div class="info fl">
		<p class="text c-white">{!$reference['name']},<br />{!$reference['description']}</p>
		<p class="tag c-dark">{!$reference['category']}</p>
	</div>
	<br class="cb">
</div>
<div n:if="!$iterator->last" class="line line2">&nbsp;</div>
{/foreach}

<div class="content">
	<!-- 
	<div class="pager">
		<ul>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">1</a></li>
		</ul>
	</div>
	<br class="cb"> 
	-->
	
	<img src="{$basePath}/img/feathers.png" id="feathers">
</div>

{/block}