{block title}References{/block}

{block content}

<div id="top" class="content">
	<div class="col-wide left">
		<h2>Get <span class="c-dark">in touch!</span></h2>
		<div class="taj col-inner bright">
			<p>Feel free to contact me. Leave a message if you want to <span class="c-dark">hire me</span> or if you just simply want to say hi and I will get back to you as soon as possible.</p>
			
			<form class="contact">
				<input name="name" type="text" value="Your name (required)"><br>
				<input name="email" type="email" value="Your e-mail address (required)"><br>
				<input name="subject" type="text" value="Subject"><br>
				<textarea name="message">Anything to say? (message required)</textarea><br>
				<button type="submit">SEND MESSAGE</button>
			</form>
		</div>
	</div>

	<div class="col-narrow right nohead">
		<div class="col-inner">
			<p>
				My contact details:
			</p>
			<p>
				<span class="c-dark">Marián Čepa</span> - designer<br>
				Mail: info@mariancepa.com<br>
				ICQ: <span class="c-dark">196-339-055</span><br>
				Skype: <span class="c-dark">xmayo90</span><br>
				Jabber: <span class="c-dark">xmayo@jabim.sk</span><br>
				Twitter: <span class="c-dark">eMCepa</span><br>
				Facebook: <span class="c-dark">eMCepa</span><br>
				Current location: <span class="c-dark">Brno (CZ)</span><br>
			</p>
			<p class="border-bottom">
				Current status: <span class="c-dark">Free for hire</span>
			</p>
			<p class="social-icons border-bottom">
				<a href="#" class="facebook"><img src="{$basePath}/img/ico-fb.png" title="Facebook"></a>
				<a href="#" class="twitter"><img src="{$basePath}/img/ico-twitter.png" title="Twitter"></a>
				<a href="#" class="lastfm"><img src="{$basePath}/img/ico-lastfm.png" title="Last.fm"></a>
				<a href="#" class="youtube"><img src="{$basePath}/img/ico-yt.png" title="YouTube"></a>
				<a href="#" class="picasa"><img src="{$basePath}/img/ico-picasa.png" title="Picasa"></a>
			</p>
		</div>
	</div>
	<br class="cb">
</div>

<div id="line2" class="line">&nbsp;</div>


<div class="content">
	<h2>Partners <span class="c-dark">&amp; Friends</span></h2>
	<div class="col left bright">
		<div class="col-inner bright">
			<span class="c-dark">Your Ideas</span> - lorem ipsum dolor [yourideas.hu]<br>
			<span class="c-dark">Misa Svec</span> - lorem ipsum dolor [yoursite.cz]<br>
			<span class="c-dark">Martin Kačmar</span> - lorem ipsum dolor [kacmar.sk]<br>
			<span class="c-dark">Roman Sládeček</span> - infoweb [romansladecek.com]<br>
		</div>
	</div>
	<div class="col right">
		<div class="col-inner">
			<span class="c-dark">Your Ideas</span> - lorem ipsum dolor [yourideas.hu]<br>
			<span class="c-dark">Misa Svec</span> - lorem ipsum dolor [yoursite.cz]<br>
			<span class="c-dark">Martin Kačmar</span> - lorem ipsum dolor [kacmar.sk]<br>
			<span class="c-dark">Roman Sládeček</span> - infoweb [romansladecek.com]<br>
		</div>
	</div>
	<br class="cb">
</div>

{/block}