{block title}{_"Get in touch title"}{/block}

{block content}

<div id="top" class="content">
	<div class="col-wide left">
		<h2>{!_"Get in touch"}</h2>
		<div class="taj col-inner bright">
			{!_"Form intro"}
			
			{widget contactForm}
		</div>
	</div>

	<div class="col-narrow right nohead">
		<div class="col-inner">
			<p>
				{!_"My contact details"}:
			</p>
			<p>
				{!_"Marian Cepa - designer"}<br />
				E-mail: info@mariancepa.com<br />
				ICQ: <span class="c-dark">196-339-055</span><br />
				Skype: <span class="c-dark">xmayo90</span><br />
				Jabber: <span class="c-dark">xmayo@jabim.sk</span><br />
				Twitter: <span class="c-dark">eMCepa</span><br />
				Facebook: <span class="c-dark">eMCepa</span><br />
				{_"Current location"}: <span class="c-dark">Brno (CZ)</span><br />
			</p>
			<p class="border-bottom">
				{_"Current status"}: <span class="c-dark">{_"status"}</span>
			</p>
			{include '../block_social.phtml'}
		</div>
	</div>
	<br class="cb">
</div>

<div id="line2" class="line">&nbsp;</div>

<div class="content">
	<h2>{!_"Partners and friends"}</h2>
	<div class="col left bright">
		<div class="col-inner bright">
			{!_"links-left"}
		</div>
	</div>
	<div class="col right">
		<div class="col-inner">
			{!_"links-right"}
		</div>
	</div>
	<br class="cb">
</div>

{/block}