<a href="#" class="facebook"><img src="{$basePath}/img/ico-fb.png" title="Facebook"></a>
<a href="#" class="twitter"><img src="{$basePath}/img/ico-twitter.png" title="Twitter"></a>
<a href="#" class="lastfm"><img src="{$basePath}/img/ico-lastfm.png" title="Last.fm"></a>
<a href="#" class="youtube"><img src="{$basePath}/img/ico-yt.png" title="YouTube"></a>
<a href="#" class="picasa"><img src="{$basePath}/img/ico-picasa.png" title="Picasa"></a>