<p class="social-icons border-bottom">
	<a href="http://www.facebook.com/pages/MarianCepa-designer/125023284209403?ref=ts" class="facebook">&nbsp;</a>
	<a href="http://twitter.com/eMCepa" class="twitter">&nbsp;</a>
	<a href="#" class="deviantart">&nbsp;</a>
	<a href="http://www.last.fm/user/xmayo" class="lastfm">&nbsp;</a>
	<a href="http://www.youtube.com/user/xmayo" class="youtube">&nbsp;</a>
	<a href="#" class="picasa" title="Inactive" onclick="javascript: return false;">&nbsp;</a>
</p>