<p class="social-icons border-bottom">
	<a href="http://www.facebook.com/pages/MarianCepa-designer/125023284209403?ref=ts" class="facebook" target="_blank">&nbsp;</a>
	<a href="http://twitter.com/eMCepa" class="twitter" target="_blank">&nbsp;</a>
	<a href="http://emcepa.deviantart.com/" class="deviantart" target="_blank">&nbsp;</a>
	<a href="http://www.last.fm/user/xmayo" class="lastfm" target="_blank">&nbsp;</a>
	<a href="http://www.youtube.com/user/xmayo" class="youtube" target="_blank">&nbsp;</a>
	<a href="#" class="picasa" title="Inactive" target="_blank" onclick="javascript: return false;">&nbsp;</a>
</p>