{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}


{if $paginator->pageCount > 1}
<div class="pager">
<ul class="pager">
	{foreach $steps as $step}
	<li><a href="{link this, 'page' => $step}" {if $step == $paginator->page}class="active"{/if}>{$step}</a></li>
	{if $iterator->nextValue > $step + 1}<li><span>…</span></li>{/if}
	{/foreach}
</ul>
</div>
{/if}

